name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to DigitalOcean Kubernetes
      uses: matootie/dokube@v1.3.4
      with:
        clusterName: k8s-bergen
        namespace: apps
        personalAccessToken: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
